import { default as ErrorRpcSDKZhongBaiActivityRechargeRebateAdd } from './ErrorRpcSDKZhongBaiActivityRechargeRebateAdd';
import { default as ErrorRpcSDKZhongBaiActivityRechargeRebatemodify } from './ErrorRpcSDKZhongBaiActivityRechargeRebatemodify';
import { default as ErrorRpcSDKZhongBaiActivityRechargeRebateQuery } from './ErrorRpcSDKZhongBaiActivityRechargeRebateQuery';
import { default as ErrorRpcSDKZhongBaiAuthGetLoginVerifyCode } from './ErrorRpcSDKZhongBaiAuthGetLoginVerifyCode';
import { default as ErrorRpcSDKZhongBaiAuthLoginWithVerifyCode } from './ErrorRpcSDKZhongBaiAuthLoginWithVerifyCode';
import { default as ErrorRpcSDKZhongBaiAuthLogout } from './ErrorRpcSDKZhongBaiAuthLogout';
import { default as ErrorRpcSDKZhongBaiPermissionAdd } from './ErrorRpcSDKZhongBaiPermissionAdd';
import { default as ErrorRpcSDKZhongBaiPermissionDelete } from './ErrorRpcSDKZhongBaiPermissionDelete';
import { default as ErrorRpcSDKZhongBaiPermissionModify } from './ErrorRpcSDKZhongBaiPermissionModify';
import { default as ErrorRpcSDKZhongBaiPermissionQuery } from './ErrorRpcSDKZhongBaiPermissionQuery';
import { default as ErrorRpcSDKZhongBaiPOSMachineAdd } from './ErrorRpcSDKZhongBaiPOSMachineAdd';
import { default as ErrorRpcSDKZhongBaiPOSMachineDelete } from './ErrorRpcSDKZhongBaiPOSMachineDelete';
import { default as ErrorRpcSDKZhongBaiPOSMachineExport } from './ErrorRpcSDKZhongBaiPOSMachineExport';
import { default as ErrorRpcSDKZhongBaiPOSMachineFreeze } from './ErrorRpcSDKZhongBaiPOSMachineFreeze';
import { default as ErrorRpcSDKZhongBaiPOSMachineQuery } from './ErrorRpcSDKZhongBaiPOSMachineQuery';
import { default as ErrorRpcSDKZhongBaiPOSMachineUnFreeze } from './ErrorRpcSDKZhongBaiPOSMachineUnFreeze';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeExport } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeExport';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQuery } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQueryReceiveFabricationStartCard } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQueryReceiveFabricationStartCard';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReceiveByFabricationID } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReceiveByFabricationID';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExport } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExport';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExportCardDetail } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExportCardDetail';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordQuery } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReturnCard } from './ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReturnCard';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardTypeAdd } from './ErrorRpcSDKZhongBaiPrePaidCardCardTypeAdd';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardTypeExport } from './ErrorRpcSDKZhongBaiPrePaidCardCardTypeExport';
import { default as ErrorRpcSDKZhongBaiPrePaidCardCardTypeQuery } from './ErrorRpcSDKZhongBaiPrePaidCardCardTypeQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationApply } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationApply';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationExport } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationExport';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationExportForFabricate } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationExportForFabricate';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationQuery } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationQueryStartCard } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationQueryStartCard';
import { default as ErrorRpcSDKZhongBaiPrePaidCardFabricationReceiveEntityCard } from './ErrorRpcSDKZhongBaiPrePaidCardFabricationReceiveEntityCard';
import { default as ErrorRpcSDKZhongBaiPrePaidCardOperationBatchFreeze } from './ErrorRpcSDKZhongBaiPrePaidCardOperationBatchFreeze';
import { default as ErrorRpcSDKZhongBaiPrePaidCardOperationBatchUnFreeze } from './ErrorRpcSDKZhongBaiPrePaidCardOperationBatchUnFreeze';
import { default as ErrorRpcSDKZhongBaiPrePaidCardOperationFreeze } from './ErrorRpcSDKZhongBaiPrePaidCardOperationFreeze';
import { default as ErrorRpcSDKZhongBaiPrePaidCardOperationQuery } from './ErrorRpcSDKZhongBaiPrePaidCardOperationQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardOperationUnFreeze } from './ErrorRpcSDKZhongBaiPrePaidCardOperationUnFreeze';
import { default as ErrorRpcSDKZhongBaiPrePaidCardQueryCard } from './ErrorRpcSDKZhongBaiPrePaidCardQueryCard';
import { default as ErrorRpcSDKZhongBaiPrePaidCardStockExport } from './ErrorRpcSDKZhongBaiPrePaidCardStockExport';
import { default as ErrorRpcSDKZhongBaiPrePaidCardStockQuery } from './ErrorRpcSDKZhongBaiPrePaidCardStockQuery';
import { default as ErrorRpcSDKZhongBaiPrePaidCardTradeConsume } from './ErrorRpcSDKZhongBaiPrePaidCardTradeConsume';
import { default as ErrorRpcSDKZhongBaiPrePaidCardTradeRecharge } from './ErrorRpcSDKZhongBaiPrePaidCardTradeRecharge';
import { default as ErrorRpcSDKZhongBaiPrePaidCardTradeSellCard } from './ErrorRpcSDKZhongBaiPrePaidCardTradeSellCard';
import { default as ErrorRpcSDKZhongBaiReconciliationGetChart } from './ErrorRpcSDKZhongBaiReconciliationGetChart';
import { default as ErrorRpcSDKZhongBaiRoleAdd } from './ErrorRpcSDKZhongBaiRoleAdd';
import { default as ErrorRpcSDKZhongBaiRoleFreeze } from './ErrorRpcSDKZhongBaiRoleFreeze';
import { default as ErrorRpcSDKZhongBaiRoleModify } from './ErrorRpcSDKZhongBaiRoleModify';
import { default as ErrorRpcSDKZhongBaiRoleQuery } from './ErrorRpcSDKZhongBaiRoleQuery';
import { default as ErrorRpcSDKZhongBaiRoleUnFreeze } from './ErrorRpcSDKZhongBaiRoleUnFreeze';
import { default as ErrorRpcSDKZhongBaiSmsGetModifyLoginPasswordVerifyCode } from './ErrorRpcSDKZhongBaiSmsGetModifyLoginPasswordVerifyCode';
import { default as ErrorRpcSDKZhongBaiStoreAddStore } from './ErrorRpcSDKZhongBaiStoreAddStore';
import { default as ErrorRpcSDKZhongBaiStoreBrandAdd } from './ErrorRpcSDKZhongBaiStoreBrandAdd';
import { default as ErrorRpcSDKZhongBaiStoreBrandDelete } from './ErrorRpcSDKZhongBaiStoreBrandDelete';
import { default as ErrorRpcSDKZhongBaiStoreBrandQuery } from './ErrorRpcSDKZhongBaiStoreBrandQuery';
import { default as ErrorRpcSDKZhongBaiStoreExport } from './ErrorRpcSDKZhongBaiStoreExport';
import { default as ErrorRpcSDKZhongBaiStoreFreeze } from './ErrorRpcSDKZhongBaiStoreFreeze';
import { default as ErrorRpcSDKZhongBaiStoreModify } from './ErrorRpcSDKZhongBaiStoreModify';
import { default as ErrorRpcSDKZhongBaiStoreQuery } from './ErrorRpcSDKZhongBaiStoreQuery';
import { default as ErrorRpcSDKZhongBaiStoreUnFreeze } from './ErrorRpcSDKZhongBaiStoreUnFreeze';
import { default as ErrorRpcSDKZhongBaiTransactionConsumeExportConsumeDetail } from './ErrorRpcSDKZhongBaiTransactionConsumeExportConsumeDetail';
import { default as ErrorRpcSDKZhongBaiTransactionExport } from './ErrorRpcSDKZhongBaiTransactionExport';
import { default as ErrorRpcSDKZhongBaiTransactionNotify } from './ErrorRpcSDKZhongBaiTransactionNotify';
import { default as ErrorRpcSDKZhongBaiTransactionQuery } from './ErrorRpcSDKZhongBaiTransactionQuery';
import { default as ErrorRpcSDKZhongBaiTransactionRechargeExportRechargeDetail } from './ErrorRpcSDKZhongBaiTransactionRechargeExportRechargeDetail';
import { default as ErrorRpcSDKZhongBaiUserAddStoreUser } from './ErrorRpcSDKZhongBaiUserAddStoreUser';
import { default as ErrorRpcSDKZhongBaiUserFreeze } from './ErrorRpcSDKZhongBaiUserFreeze';
import { default as ErrorRpcSDKZhongBaiUserModifyLoginPassword } from './ErrorRpcSDKZhongBaiUserModifyLoginPassword';
import { default as ErrorRpcSDKZhongBaiUserModifyStoreUser } from './ErrorRpcSDKZhongBaiUserModifyStoreUser';
import { default as ErrorRpcSDKZhongBaiUserQuery } from './ErrorRpcSDKZhongBaiUserQuery';
import { default as ErrorRpcSDKZhongBaiUserResetLoginPassword } from './ErrorRpcSDKZhongBaiUserResetLoginPassword';
import { default as ErrorRpcSDKZhongBaiUserUnFreeze } from './ErrorRpcSDKZhongBaiUserUnFreeze';

let CodesMap = {};
CodesMap[ErrorRpcSDKZhongBaiActivityRechargeRebateAdd.method] = ErrorRpcSDKZhongBaiActivityRechargeRebateAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiActivityRechargeRebatemodify.method] = ErrorRpcSDKZhongBaiActivityRechargeRebatemodify.codes;
CodesMap[ErrorRpcSDKZhongBaiActivityRechargeRebateQuery.method] = ErrorRpcSDKZhongBaiActivityRechargeRebateQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiAuthGetLoginVerifyCode.method] = ErrorRpcSDKZhongBaiAuthGetLoginVerifyCode.codes;
CodesMap[ErrorRpcSDKZhongBaiAuthLoginWithVerifyCode.method] = ErrorRpcSDKZhongBaiAuthLoginWithVerifyCode.codes;
CodesMap[ErrorRpcSDKZhongBaiAuthLogout.method] = ErrorRpcSDKZhongBaiAuthLogout.codes;
CodesMap[ErrorRpcSDKZhongBaiPermissionAdd.method] = ErrorRpcSDKZhongBaiPermissionAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiPermissionDelete.method] = ErrorRpcSDKZhongBaiPermissionDelete.codes;
CodesMap[ErrorRpcSDKZhongBaiPermissionModify.method] = ErrorRpcSDKZhongBaiPermissionModify.codes;
CodesMap[ErrorRpcSDKZhongBaiPermissionQuery.method] = ErrorRpcSDKZhongBaiPermissionQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineAdd.method] = ErrorRpcSDKZhongBaiPOSMachineAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineDelete.method] = ErrorRpcSDKZhongBaiPOSMachineDelete.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineExport.method] = ErrorRpcSDKZhongBaiPOSMachineExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineFreeze.method] = ErrorRpcSDKZhongBaiPOSMachineFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineQuery.method] = ErrorRpcSDKZhongBaiPOSMachineQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPOSMachineUnFreeze.method] = ErrorRpcSDKZhongBaiPOSMachineUnFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeExport.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQueryReceiveFabricationStartCard.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeQueryReceiveFabricationStartCard.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReceiveByFabricationID.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReceiveByFabricationID.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExport.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExportCardDetail.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordExportCardDetail.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeRecordQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReturnCard.method] = ErrorRpcSDKZhongBaiPrePaidCardCardDistributeReturnCard.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardTypeAdd.method] = ErrorRpcSDKZhongBaiPrePaidCardCardTypeAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardTypeExport.method] = ErrorRpcSDKZhongBaiPrePaidCardCardTypeExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardCardTypeQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardCardTypeQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationApply.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationApply.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationExport.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationExportForFabricate.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationExportForFabricate.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationQueryStartCard.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationQueryStartCard.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardFabricationReceiveEntityCard.method] = ErrorRpcSDKZhongBaiPrePaidCardFabricationReceiveEntityCard.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardOperationBatchFreeze.method] = ErrorRpcSDKZhongBaiPrePaidCardOperationBatchFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardOperationBatchUnFreeze.method] = ErrorRpcSDKZhongBaiPrePaidCardOperationBatchUnFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardOperationFreeze.method] = ErrorRpcSDKZhongBaiPrePaidCardOperationFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardOperationQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardOperationQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardOperationUnFreeze.method] = ErrorRpcSDKZhongBaiPrePaidCardOperationUnFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardQueryCard.method] = ErrorRpcSDKZhongBaiPrePaidCardQueryCard.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardStockExport.method] = ErrorRpcSDKZhongBaiPrePaidCardStockExport.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardStockQuery.method] = ErrorRpcSDKZhongBaiPrePaidCardStockQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardTradeConsume.method] = ErrorRpcSDKZhongBaiPrePaidCardTradeConsume.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardTradeRecharge.method] = ErrorRpcSDKZhongBaiPrePaidCardTradeRecharge.codes;
CodesMap[ErrorRpcSDKZhongBaiPrePaidCardTradeSellCard.method] = ErrorRpcSDKZhongBaiPrePaidCardTradeSellCard.codes;
CodesMap[ErrorRpcSDKZhongBaiReconciliationGetChart.method] = ErrorRpcSDKZhongBaiReconciliationGetChart.codes;
CodesMap[ErrorRpcSDKZhongBaiRoleAdd.method] = ErrorRpcSDKZhongBaiRoleAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiRoleFreeze.method] = ErrorRpcSDKZhongBaiRoleFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiRoleModify.method] = ErrorRpcSDKZhongBaiRoleModify.codes;
CodesMap[ErrorRpcSDKZhongBaiRoleQuery.method] = ErrorRpcSDKZhongBaiRoleQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiRoleUnFreeze.method] = ErrorRpcSDKZhongBaiRoleUnFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiSmsGetModifyLoginPasswordVerifyCode.method] = ErrorRpcSDKZhongBaiSmsGetModifyLoginPasswordVerifyCode.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreAddStore.method] = ErrorRpcSDKZhongBaiStoreAddStore.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreBrandAdd.method] = ErrorRpcSDKZhongBaiStoreBrandAdd.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreBrandDelete.method] = ErrorRpcSDKZhongBaiStoreBrandDelete.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreBrandQuery.method] = ErrorRpcSDKZhongBaiStoreBrandQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreExport.method] = ErrorRpcSDKZhongBaiStoreExport.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreFreeze.method] = ErrorRpcSDKZhongBaiStoreFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreModify.method] = ErrorRpcSDKZhongBaiStoreModify.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreQuery.method] = ErrorRpcSDKZhongBaiStoreQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiStoreUnFreeze.method] = ErrorRpcSDKZhongBaiStoreUnFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiTransactionConsumeExportConsumeDetail.method] = ErrorRpcSDKZhongBaiTransactionConsumeExportConsumeDetail.codes;
CodesMap[ErrorRpcSDKZhongBaiTransactionExport.method] = ErrorRpcSDKZhongBaiTransactionExport.codes;
CodesMap[ErrorRpcSDKZhongBaiTransactionNotify.method] = ErrorRpcSDKZhongBaiTransactionNotify.codes;
CodesMap[ErrorRpcSDKZhongBaiTransactionQuery.method] = ErrorRpcSDKZhongBaiTransactionQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiTransactionRechargeExportRechargeDetail.method] = ErrorRpcSDKZhongBaiTransactionRechargeExportRechargeDetail.codes;
CodesMap[ErrorRpcSDKZhongBaiUserAddStoreUser.method] = ErrorRpcSDKZhongBaiUserAddStoreUser.codes;
CodesMap[ErrorRpcSDKZhongBaiUserFreeze.method] = ErrorRpcSDKZhongBaiUserFreeze.codes;
CodesMap[ErrorRpcSDKZhongBaiUserModifyLoginPassword.method] = ErrorRpcSDKZhongBaiUserModifyLoginPassword.codes;
CodesMap[ErrorRpcSDKZhongBaiUserModifyStoreUser.method] = ErrorRpcSDKZhongBaiUserModifyStoreUser.codes;
CodesMap[ErrorRpcSDKZhongBaiUserQuery.method] = ErrorRpcSDKZhongBaiUserQuery.codes;
CodesMap[ErrorRpcSDKZhongBaiUserResetLoginPassword.method] = ErrorRpcSDKZhongBaiUserResetLoginPassword.codes;
CodesMap[ErrorRpcSDKZhongBaiUserUnFreeze.method] = ErrorRpcSDKZhongBaiUserUnFreeze.codes;

export default CodesMap;
